version: '3.4'

services:
  db:
    image: mysql:8.0
    container_name: go-job-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: murilo
      MYSQL_PASSWORD: felpeto
      MYSQL_DATABASE: go-job
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8111:8080"
  swagger-ui:
    image: mrin9/rapidoc
    container_name: go-job-swagger
    environment:
      SPEC_URL: http://localhost:5000/v1/openapi
      RAPIDOC_OPTIONS: "theme='dark' allow-authentication='true' api-key-name='Authorization' api-key-value='Bearer XPTO' api-key-location='header' "
    ports:
      - "8112:80"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      NGINX_PORT: 5000
      NGINX_HOST: 127.0.0.1
    ports:
      - "5000:5000"